title: Ebenezer
description: Liceu & Instituto Médio Politécnico
email: info@ebenezer.co.mz
url: https://ebenezer.co.mz

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-email-protect
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics

collections_dir: collections
collections:
  main:
  galeria:
  location:
  # Liceu
  sobre_liceu:
  servicos_liceu:
  mensalidade_liceu:
  transporte_liceu:
  # IMEPE
  sobre_imepe:
  cursos_imepe:
  mensalidade_imepe:

sass:
  sass_dir: assets/_sass
  style: compressed

pagination:
  enabled: true
  per_page: 15
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bower_components